import type { FeatureSchemaConfig } from "@/lib/import-engine/types";

export const callLogSchema: FeatureSchemaConfig = {
  featureKey: "call_log",
  featureLabel: "Call Log",
  dbTable: "staff_call_logs",
  customerTable: "customers",
  customerIdColumn: "customerId",
  dedupeKeys: ["phone"],
  columns: [
    {
      frontendLabel: "Customer Name",
      dbColumn: "name",
      type: "string",
      required: false,
      isCustomerField: true,
      synonyms: ["customer name", "client name", "party name", "member name", "guest name"],
    },
    {
      frontendLabel: "Customer Phone",
      dbColumn: "phone",
      type: "phone",
      required: true,
      isCustomerField: true,
      isDedupeKey: true,
      synonyms: [
        "mobile",
        "mob",
        "contact",
        "phone number",
        "cell",
        "mobile no",
        "contact no",
        "whatsapp",
        "customer phone",
      ],
    },
    {
      frontendLabel: "Customer Email",
      dbColumn: "email",
      type: "email",
      required: false,
      isCustomerField: true,
      isDedupeKey: false,
      synonyms: ["email", "e-mail", "email address", "mail"],
    },
    {
      frontendLabel: "Call Date",
      dbColumn: "createdAt",
      type: "date",
      required: false,
      dateFormats: ["dd/MM/yyyy", "MM-dd-yyyy", "yyyy-MM-dd"],
      synonyms: ["call date", "called on", "date", "call dt", "log date"],
    },
    {
      frontendLabel: "Call Duration",
      dbColumn: "durationSeconds",
      type: "number",
      required: false,
      synonyms: ["duration", "call duration", "talk time", "call time", "length", "minutes"],
    },
    {
      frontendLabel: "Call Outcome",
      dbColumn: "answered",
      type: "string",
      required: false,
      synonyms: [
        "outcome",
        "call outcome",
        "result",
        "status",
        "call status",
        "disposition",
        "answered",
      ],
    },
    {
      frontendLabel: "Agent Name",
      dbColumn: "staffId",
      type: "lookup",
      required: false,
      lookupTable: "staff",
      lookupDisplayColumn: "name",
      lookupKeyColumn: "id",
      synonyms: [
        "agent",
        "agent name",
        "staff",
        "employee",
        "consultant",
        "rso",
        "handled by",
        "caller",
      ],
    },
    {
      frontendLabel: "Notes",
      dbColumn: "feedback",
      type: "string",
      required: false,
      synonyms: ["notes", "note", "remarks", "comments", "feedback", "call notes"],
    },
  ],
};
