import type { FeatureSchemaConfig } from "@/lib/import-engine/types";

export const visitLogSchema: FeatureSchemaConfig = {
  featureKey: "visit_log",
  featureLabel: "Visit Log",
  supabaseTable: "visits",
  customerTable: "customers",
  customerIdColumn: "customerId",
  dedupeKeys: ["phone"],
  columns: [
    {
      frontendLabel: "Customer Name",
      supabaseColumn: "name",
      type: "string",
      required: true,
      isCustomerField: true,
      synonyms: [
        "customer name",
        "client name",
        "party name",
        "member name",
        "guest name",
        "visitor name",
        "cust name",
      ],
    },
    {
      frontendLabel: "Customer Phone",
      supabaseColumn: "phone",
      type: "phone",
      required: true,
      isCustomerField: true,
      isDedupeKey: true,
      synonyms: [
        "mobile",
        "mob",
        "contact",
        "phone number",
        "cell",
        "mobile no",
        "mob no",
        "contact no",
        "whatsapp",
        "ph no",
        "customer phone",
      ],
    },
    {
      frontendLabel: "Customer Email",
      supabaseColumn: "email",
      type: "email",
      required: false,
      isCustomerField: true,
      isDedupeKey: false,
      synonyms: ["email", "e-mail", "email address", "mail", "email id"],
    },
    {
      frontendLabel: "Visit Date",
      supabaseColumn: "visitDate",
      type: "date",
      required: true,
      dateFormats: ["dd/MM/yyyy", "MM-dd-yyyy", "yyyy-MM-dd", "d MMM yyyy"],
      synonyms: [
        "date",
        "visit",
        "appointment date",
        "date of visit",
        "visit dt",
        "visited on",
        "visit date time",
      ],
    },
    {
      frontendLabel: "Staff Name",
      supabaseColumn: "staffId",
      type: "lookup",
      required: true,
      lookupTable: "staff",
      lookupDisplayColumn: "name",
      lookupKeyColumn: "id",
      synonyms: [
        "staff",
        "employee",
        "consultant",
        "attended by",
        "served by",
        "rso name",
        "sales person",
        "handled by",
      ],
    },
    {
      frontendLabel: "Service/Product",
      supabaseColumn: "productsExplored",
      type: "string",
      required: false,
      synonyms: [
        "product",
        "service",
        "item",
        "category",
        "products explored",
        "article",
        "collection",
        "sku",
      ],
    },
    {
      frontendLabel: "Purchase Amount",
      supabaseColumn: "transactionAmount",
      type: "number",
      required: false,
      synonyms: [
        "amount",
        "amt",
        "purchase",
        "sale",
        "total",
        "value",
        "bill amt",
        "revenue",
        "transaction amount",
      ],
    },
    {
      frontendLabel: "Notes",
      supabaseColumn: "staffNotes",
      type: "string",
      required: false,
      synonyms: ["notes", "note", "remarks", "comments", "staff notes", "observations"],
    },
  ],
};
