export const content = {
  common: {
    appName: "MyStore",
    loading: "Loading…",
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    confirm: "Confirm",
    delete: "Delete",
    edit: "Edit",
    export: "Export",
    search: "Search",
    filter: "Filter",
    noResults: "No results found",
    back: "Back",
    next: "Next",
    previous: "Previous",
    submit: "Submit",
    viewAll: "View all",
    signOut: "Sign out",
  },
  assignStaff: {
    action: "Assign",
    title: "Assign to staff",
    description: "Move {name} from {staff} to another team member.",
    unassigned: "unassigned staff",
    staffLabel: "Assign to",
    staffPlaceholder: "Select staff member",
    current: "current",
    hint: "The customer and any open follow-up will move to the selected staff member.",
    confirm: "Assign customer",
    successTitle: "Customer assigned",
    successDescription: "{name} is now assigned to {staff}.",
    errorTitle: "Could not assign customer",
  },
  dashboardNotifications: {
    title: "Reminders & follow-ups",
    empty: "You're all caught up — no pending calls or follow-ups.",
    overdueFollowUps: {
      title: "Overdue follow-ups",
      description: "{count} follow-up(s) past due",
      descriptionStore: "{count} overdue follow-up(s) across your store",
    },
    dueTodayFollowUps: {
      title: "Follow-ups due today",
      description: "{count} follow-up(s) scheduled for today",
    },
    followUpCalls: {
      title: "Follow-up call queue",
      description: "{count} customer(s) waiting for a follow-up call",
    },
    notAnsweredCalls: {
      title: "Not answered calls",
      description: "{count} customer(s) did not answer — call again",
    },
    birthdays: {
      title: "Birthday reminders",
      description: "{count} of your customers have a birthday this month",
    },
    anniversaries: {
      title: "Anniversary reminders",
      description: "{count} of your customers have an anniversary this month",
    },
    missedBirthdays: {
      title: "Missed birthday calls",
      description: "{count} birthday(s) passed without a successful call",
    },
    missedAnniversaries: {
      title: "Missed anniversary calls",
      description: "{count} anniversary(ies) passed without a successful call",
    },
    filters: {
      selectPrompt: "Select a category above to view items.",
      empty: "Nothing in this category right now.",
      viewAll: "View all",
      previewHint: "Showing first {shown} of {total} — open the full list for more.",
      guide:
        "Tasks with a due date appear under follow-ups. Customers to call back appear in the call queues.",
    },
    categoryHints: {
      overdue_follow_ups: "Scheduled tasks past their due date — close or reschedule them here.",
      due_today_follow_ups: "Follow-up tasks scheduled for today.",
      follow_up_calls:
        "Customers with an open follow-up to call. Use the Calls page to dial and log outcomes.",
      not_answered_calls:
        "Last call was not answered. Call again — this takes priority over the follow-up queue.",
      birthdays: "Customers with a birthday this month who still need a call.",
      anniversaries: "Customers with an anniversary this month who still need a call.",
    },
  },
  auth: {
    login: {
      title: "Sign in to MyStore",
      subtitle: "Use your work email and password",
      submitLabel: "Sign In",
      errorInvalid: "Invalid email or password",
      errorMissingProfile:
        "No staff account is linked to this email. Ask your store manager to add you or resend your invite.",
      errorIncompleteProfile:
        "Your account setup is incomplete. Ask your store manager to finish staff setup for this email.",
      errorInactive:
        "No staff account is linked to this email. Ask your store manager to add you or resend your invite.",
      errorDeactivated:
        "Your account has been deactivated. Contact your store manager or business owner.",
      errorGeneric: "Sign-in failed. Please try again.",
      errorWrongPortal:
        "This account uses a different dashboard. Sign in from the correct portal link for your role.",
      errorSessionExpired:
        "Your session expired. Sign in again with your email and password.",
      forgotPassword: "Forgot password?",
      resetSuccess: "Your password has been updated. Sign in with your new password.",
      forgotPasswordEmailRequired:
        "Enter your email first, then request a password reset link.",
      resetEmailSent:
        "If an account exists for that email, a password reset link has been sent. Check your inbox.",
      resetEmailSentHint:
        "Open the link once from your email. You can use any browser after the link arrives.",
      resetEmailCooldown: "Wait {seconds}s before requesting another reset link.",
      resetEmailError: "Could not send the reset email. Try again in a few minutes.",
      resetEmailRateLimited:
        "Too many reset requests. Please wait a few minutes and try again.",
      resetEmailRedirectError:
        "Password reset email could not be sent. Check SMTP settings and try again.",
    },
    resetPassword: {
      title: "Reset your password",
      subtitle: "Choose a new password for your account",
      passwordLabel: "New password",
      passwordPlaceholder: "Enter new password",
      confirmPasswordLabel: "Confirm password",
      confirmPasswordPlaceholder: "Re-enter new password",
      submitLabel: "Update password",
      backToSignIn: "Back to sign in",
      errorGeneric: "Could not update password. Try again.",
      errorMismatch: "Passwords do not match.",
      errorNoSession:
        "This reset link is invalid or has expired. Request a new one from the sign-in page.",
      errorAuthCallback:
        "This reset link could not be verified. Request a new link from the sign-in page and open it once.",
    },
    staff: {
      title: "Staff Login",
      subtitle: "Sign in to access the staff portal",
      idLabel: "Employee Name",
      idPlaceholder: "Enter employee name",
      passwordLabel: "Employee ID",
      passwordPlaceholder: "Enter employee ID",
      submitLabel: "Sign In",
      errorInvalid: "Invalid employee name or ID",
    },
    store: {
      title: "Store Login",
      subtitle: "Access your store dashboard",
      idLabel: "Store Name",
      idPlaceholder: "Enter store name",
      passwordLabel: "Store Pincode",
      passwordPlaceholder: "Enter store pincode",
      submitLabel: "Access Dashboard",
      errorInvalid: "Invalid store name or pincode",
    },
    admin: {
      title: "Consultant Login",
      subtitle: "Portfolio access for all client stores",
      idLabel: "Admin Email",
      idPlaceholder: "Enter admin email",
      passwordLabel: "Password",
      passwordPlaceholder: "Enter password",
      submitLabel: "Sign In to Admin",
      errorInvalid: "Invalid admin credentials",
    },
  },
  visitForm: {
    title: "Log Customer Visit",
    subtitle: "Record visit details for analytics",
    schemeHint:
      "Primary goal: pitch Gold Harvest Scheme (GHS) and Jold Purchase Plan (JPP). Capture who you met and what was enrolled.",
    progress: "Step {current} of {total}",
    sections: {
      customer: "Customer Details",
      visit: "Visit Details",
      scheme: "Scheme Pitch & Outcome",
      noPurchase: "No-Purchase Context",
      preferences: "Product Preferences",
      followUp: "Follow-up",
    },
    fields: {
      customerName: { label: "Customer Name", placeholder: "Full name" },
      phone: { label: "Phone Number", placeholder: "10-digit mobile" },
      existingCustomerHint: "Existing customer — details prefilled",
      lookingUpCustomer: "Looking up customer…",
      customerType: {
        label: "Customer Type",
        options: { NEW: "New", REPEAT: "Repeat", VIP: "VIP" },
      },
      visitType: {
        label: "Visit Type",
        options: { WALK_IN: "Walk-in", APPOINTMENT: "Appointment" },
      },
      saleDate: {
        label: "Sale date",
        placeholder: "Select date",
        hint: "Select the actual sale date if you are logging a visit late.",
      },
      inTime: { label: "In Time", placeholder: "Select time" },
      outTime: { label: "Out Time", placeholder: "Select time" },
      totalDuration: { label: "Total Duration" },
      sourceChannel: {
        label: "Source / Channel",
        options: {
          ORGANIC_WALK_IN: "Organic Walk-in",
          REFERRAL: "Referral",
          SOCIAL_MEDIA: "Social Media",
          INTERNET: "Internet",
          PHONE: "Phone",
          USER_CALLS: "User Calls",
          TANISHQ_REF: "Tanishq Reference",
          CARATLANE_REF: "Caratlane Reference",
          OTHER: "Other",
        },
      },
      area: { label: "Area / Locality", placeholder: "Locality or area" },
      address: {
        label: "Address",
        placeholder: "Street, area, city, pincode",
      },
      profession: {
        label: "Profession",
        placeholder: "e.g. Teacher, Business owner",
      },
      gender: {
        label: "Gender",
        options: {
          MALE: "Male",
          FEMALE: "Female",
          OTHER: "Other",
          PREFER_NOT_TO_SAY: "Prefer not to say",
        },
      },
      ageGroup: {
        label: "Age Group",
        options: {
          "18-25": "18–25",
          "26-35": "26–35",
          "36-50": "36–50",
          "50+": "50+",
        },
      },
      dateOfBirth: { label: "Date of birth", placeholder: "Select date" },
      anniversary: { label: "Anniversary", placeholder: "Select date" },
      productsExplored: {
        label: "Products Explored",
        options: {
          BANGLES: "Bangles",
          BRACELET: "Bracelet",
          EAR_RINGS: "Ear rings",
          FINGER_RINGS: "Finger rings",
          CHAINS: "Chains",
          NECKLACE: "Necklace",
          MANGALSUTRA: "Mangalsutra",
          NOSE_PIN: "Nose pin",
          PENDANTS: "Pendants",
          COLLOR: "Collor",
          JUMKA: "Jumka",
          PENDANT_EARRINGS: "Pendant & earrings",
          NECKLACE_EARRINGS: "Necklace & earrings",
          NECKLACE_PENDANT_EARRINGS: "Necklace & pendant & earrings",
          COINS: "Coins",
          SILVER: "Silver",
        },
      },
      purchaseStatus: {
        label: "Purchase Status",
        options: {
          PURCHASED: "Purchased",
          NOT_PURCHASED: "Not Purchased",
        },
      },
      productsPurchased: { label: "Products Purchased" },
      transactionAmount: {
        label: "Transaction Amount",
        placeholder: "Enter amount",
      },
      intentTier: {
        label: "Interest Level",
        placeholder: "Select",
        options: {
          HOT: "Hot",
          WARM: "Warm",
          COLD: "Cold",
          BROWSING: "Browsing",
        },
      },
      schemesPitched: {
        label: "Schemes Pitched",
        options: {
          GHS: "GHS — Gold Harvest Scheme",
          GPP: "JPP — Jold Purchase Plan",
          NONE: "None",
        },
      },
      enrollmentOutcome: {
        label: "Outcome",
        options: {
          ENROLLED_GHS: "Enrolled in GHS",
          ENROLLED_GPP: "Enrolled in JPP",
          ENROLLED_BOTH: "Enrolled in both",
          INTERESTED: "Interested — not enrolled yet",
          DECLINED: "Declined",
          CALLBACK: "Callback requested",
        },
      },
      monthlyCommitment: {
        label: "Monthly Commitment",
        placeholder: "Enter amount",
      },
      reasonNoEnrollment: {
        label: "Reason",
        options: {
          BUDGET: "Budget constraints",
          ALREADY_ENROLLED: "Already enrolled elsewhere",
          NOT_INTERESTED: "Not interested",
          NEEDS_TIME: "Needs more time",
          TRUST_CONCERNS: "Trust / clarity concerns",
          COMPETITOR_SCHEME: "Competitor scheme",
        },
      },
      schemeCompetitorMention: {
        label: "Competitor / Alternative",
        placeholder: "Optional — other jeweller or scheme",
      },
      reasonNoPurchase: {
        label: "Reason No Purchase",
        options: {
          BUDGET: "Budget",
          DESIGN_NOT_LIKED: "Design not liked",
          EXPLORING: "Exploring",
          COMPETITOR: "Competitor",
          PAYMENT_ISSUE: "Payment issue",
          WILL_VISIT_AGAIN: "Will visit again",
        },
      },
      competitorMention: {
        label: "Competitor Mention",
        placeholder: "Optional competitor name",
      },
      purchaseOccasion: {
        label: "Purchase Occasion",
        options: {
          WEDDING: "Wedding",
          ANNIVERSARY: "Anniversary",
          GIFT: "Gift",
          SELF: "Self",
          FESTIVAL: "Festival",
        },
      },
      metalKtPref: {
        label: "Metal / KT Preference",
        options: {
          GOLD_14KT: "Gold 14KT",
          GOLD_18KT: "Gold 18KT",
          GOLD_22KT: "Gold 22KT",
          GOLD_24KT: "Gold 24KT",
          DIAMOND: "Diamond",
          SILVER: "Silver",
        },
      },
      budgetStated: {
        label: "Budget Stated",
        options: {
          UNDER_15K: "Under ₹15K",
          K15_50K: "₹15K – ₹50K",
          K50_1L: "₹50K – ₹1L",
          ABOVE_1L: "Above ₹1L",
          NOT_STATED: "Not stated",
        },
      },
      followUpNeeded: { label: "Follow-up Needed" },
      followUpDate: { label: "Follow-up Date", placeholder: "Select date" },
      staffNotes: {
        label: "Staff Notes",
        placeholder: "Additional notes (max 500 characters)",
      },
    },
    actions: {
      submit: "Submit Visit",
      logAnother: "Log Another Visit",
      viewCalls: "Go to call list",
      viewFollowUps: "View follow-up tasks",
      viewMyVisits: "View my visits",
      saving: "Saving…",
      successTitle: "Visit logged successfully",
      successMessage: "The visit has been recorded and synced.",
    },
    validation: {
      required: "This field is required",
      phoneInvalid: "Enter a valid 10-digit phone number",
      notesMaxLength: "Notes must be 500 characters or fewer",
      amountRequired: "Transaction amount is required for purchases",
    },
  },
  fieldSalesForm: {
    title: "Log Field Sale",
    subtitle:
      "Record outdoor customer interactions and GHS / JPP scheme outcomes",
    schemeHint:
      "Primary goal: pitch Gold Harvest Scheme (GHS) and Jold Purchase Plan (JPP). Capture who you met and what was enrolled.",
    progress: "Step {current} of {total}",
    sections: {
      customer: "Customer Details",
      activity: "Field Activity",
      scheme: "Scheme Pitch & Outcome",
      noEnrollment: "No-Enrollment Context",
      followUp: "Follow-up",
    },
    fields: {
      customerName: { label: "Customer Name", placeholder: "Full name" },
      phone: { label: "Phone Number", placeholder: "10-digit mobile" },
      customerType: {
        label: "Customer Type",
        options: { NEW: "New", REPEAT: "Repeat", VIP: "VIP" },
      },
      profession: {
        label: "Profession",
        placeholder: "e.g. Teacher, Business owner",
      },
      area: { label: "Area / Locality", placeholder: "Neighbourhood or territory" },
      gender: {
        label: "Gender",
        placeholder: "Select",
        options: {
          MALE: "Male",
          FEMALE: "Female",
          OTHER: "Other",
          PREFER_NOT_TO_SAY: "Prefer not to say",
        },
      },
      ageGroup: {
        label: "Age Group",
        placeholder: "Select",
        options: {
          "18-25": "18–25",
          "26-35": "26–35",
          "36-50": "36–50",
          "50+": "50+",
        },
      },
      activityType: {
        label: "Activity Type",
        options: {
          DOOR_TO_DOOR: "Door to door",
          HOUSING_SOCIETY: "Housing society",
          CORPORATE: "Corporate / office",
          EVENT_EXHIBITION: "Event / exhibition",
          MARKET_STALL: "Market stall",
          REFERRAL_MEET: "Referral meeting",
          OTHER: "Other",
        },
      },
      locationLabel: {
        label: "Location",
        placeholder: "e.g. Green Park Society, Block B",
      },
      activityDate: { label: "Activity Date" },
      startTime: { label: "Start Time" },
      endTime: { label: "End Time" },
      totalDuration: { label: "Total Duration" },
      schemesPitched: {
        label: "Schemes Pitched",
        options: {
          GHS: "GHS — Gold Harvest Scheme",
          GPP: "JPP — Jold Purchase Plan",
          NONE: "None",
        },
      },
      enrollmentOutcome: {
        label: "Outcome",
        options: {
          ENROLLED_GHS: "Enrolled in GHS",
          ENROLLED_GPP: "Enrolled in JPP",
          ENROLLED_BOTH: "Enrolled in both",
          INTERESTED: "Interested — not enrolled yet",
          DECLINED: "Declined",
          CALLBACK: "Callback requested",
        },
      },
      monthlyCommitment: {
        label: "Monthly Commitment",
        placeholder: "Enter amount",
      },
      intentTier: {
        label: "Interest Level",
        placeholder: "Select",
        options: {
          HOT: "Hot",
          WARM: "Warm",
          COLD: "Cold",
          BROWSING: "Browsing",
        },
      },
      reasonNoEnrollment: {
        label: "Reason",
        options: {
          BUDGET: "Budget constraints",
          ALREADY_ENROLLED: "Already enrolled elsewhere",
          NOT_INTERESTED: "Not interested",
          NEEDS_TIME: "Needs more time",
          TRUST_CONCERNS: "Trust / clarity concerns",
          COMPETITOR_SCHEME: "Competitor scheme",
        },
      },
      competitorMention: {
        label: "Competitor / Alternative",
        placeholder: "Optional — other jeweller or scheme",
      },
      followUpNeeded: { label: "Schedule follow-up" },
      followUpDate: { label: "Follow-up Date" },
      staffNotes: {
        label: "Staff Notes",
        placeholder: "Conversation highlights (max 500 characters)",
      },
    },
    actions: {
      submit: "Submit Field Sale",
      logAnother: "Log Another Interaction",
      saving: "Saving…",
      successTitle: "Field sale logged",
      successMessage: "Customer data and scheme outcome have been recorded.",
      viewMyFieldSales: "View my field sales",
      viewCalls: "View call list",
      viewFollowUps: "View follow-up tasks",
    },
  },
  staff: {
    shell: {
      title: "Staff Portal",
      nav: {
        home: "Home",
        calls: "Calls",
        followUps: "Follow-ups",
        logVisit: "Log visit",
      },
    },
    portal: {
      title: "What would you like to do?",
      subtitle: "Choose an action to get started",
      actions: {
        logVisit: {
          title: "Log Customer Visit",
          description: "Record walk-in or appointment details for store analytics",
          cta: "Log visit",
        },
        myVisits: {
          title: "My Visits",
          description: "Review visits you have logged and open customer profiles",
          cta: "View my visits",
        },
        callUsers: {
          title: "Call Users",
          description: "Call customers you served and log retention outcomes",
          cta: "View call list",
        },
        fieldSales: {
          title: "Log Field Sale",
          description: "Log outdoor visits and GHS / JPP enrollments in the field",
          cta: "Log field sale",
        },
        myFieldSales: {
          title: "My Field Sales",
          description: "Review field activities you logged and open customer profiles",
          cta: "View my field sales",
        },
        followUps: {
          title: "Follow-up tasks",
          description: "Dated tasks from visits and field sales — not the call queue",
          cta: "View tasks",
        },
      },
      remindersGuide:
        "Your work queue shows what needs you today. Switch to Browse all to explore each category in full.",
    },
    logVisit: {
      title: "Log a customer visit",
      subtitle: "Record walk-in or appointment details — separate from your visit history.",
    },
    myVisits: {
      title: "My visits",
      subtitle: "Visits you have logged — tap a row to view the customer profile.",
      empty: "No visits logged yet.",
      logVisit: "Log a visit",
      followUpScheduled: "Follow-up scheduled",
    },
    myFieldSales: {
      title: "My field sales",
      subtitle: "Field activities you logged — tap a row to view the customer profile.",
      empty: "No field sales logged yet.",
      logFieldSale: "Log field sale",
      followUpScheduled: "Follow-up scheduled",
      noOutcome: "No enrollment yet",
    },
    customerProfile: {
      callCustomer: "Call customer",
    },
    workQueue: {
      title: "Your work queue",
      subtitle: "Tasks and calls that need you today.",
      compactSubtitle: "Prioritized for today — tasks first, then calls.",
      browseSubtitle: "Browse each category to see everything in that bucket.",
      empty: "You're all caught up for today.",
      previewHint: "Showing {shown} of {total} items.",
      viewTasks: "All follow-up tasks",
      viewCalls: "Full call list",
      modes: {
        label: "View",
        compact: "Compact",
        browse: "Browse all",
      },
      sections: {
        overdue_task: "Overdue tasks",
        due_today_task: "Due today",
        mismatched_assignment: "Needs reassignment",
        not_answered: "Did not answer",
        follow_up_call: "Follow-up calls",
        birthday: "Birthdays this month",
        anniversary: "Anniversaries this month",
      },
      emptySection: "Nothing in this category.",
    },
    bottomNav: {
      label: "Staff navigation",
      home: "Home",
      calls: "Calls",
      log: "Log",
      more: "More",
    },
    moreSheet: {
      title: "More actions",
      searchHint: "Search any customer with ⌘K",
    },
    logSheet: {
      title: "Log activity",
      visit: "Log customer visit",
      fieldSale: "Log field sale",
    },
    notifications: {
      title: "Notifications",
      empty: "No pending items today.",
      overdue: "{count} overdue task(s)",
      dueToday: "{count} due today",
      openHome: "Open work queue",
    },
    amend: {
      title: "Edit record",
      description: "You can edit your own records within 72 hours of logging.",
      customerName: "Customer name",
      customerPhone: "Phone",
      area: "Area",
      location: "Location",
      notes: "Staff notes",
      save: "Save changes",
      saving: "Saving…",
      success: "Changes saved",
      edit: "Edit",
    },
    correctionRequest: {
      title: "Request correction",
      description: "Ask your store manager to fix {name}'s record.",
      placeholder: "Describe what needs to be corrected (min 10 characters)",
      submit: "Send request",
      sending: "Sending…",
      success: "Correction request sent to your manager",
      requestFix: "Request fix",
    },
    search: {
      button: "Search",
      title: "Search customers",
      description: "Find by name or phone",
      placeholder: "Search customers…",
      mine: "My customers",
      store: "Store lookup",
      mineHint: "Customers you have visited or logged",
      storeHint: "Any customer in your store",
      empty: "No customers found",
      error: "Search failed. Try again.",
      minChars: "Type at least 2 characters",
    },
    onboarding: {
      step1Title: "Start with your work queue",
      step1Body: "Your home screen shows what needs you today — overdue tasks, calls, and occasions — in priority order.",
      step2Title: "Log visits and field sales",
      step2Body: "Tap Log on mobile or use the action cards to record walk-ins and outdoor enrollments.",
      step3Title: "Call and close the loop",
      step3Body: "Tap Call on any row to dial, log the outcome, and update follow-ups. Use ⌘K to find any store customer.",
    },
    followUps: {
      title: "Follow-up tasks",
      subtitle: "Scheduled follow-ups assigned to you",
      guide:
        "These are dated tasks from visit or field-sale forms. To call customers from your retention list, use Calls → Follow-up call queue.",
      empty: "No overdue follow-ups right now.",
      emptyDueToday: "No follow-ups due today.",
      emptyOpen: "No open follow-ups right now.",
      emptyMismatched: "No mismatched assignments right now.",
      filters: {
        overdue: "Overdue",
        due_today: "Due today",
        open: "All open",
        mismatched: "Needs reassignment",
      },
      dueLabel: "Due",
      assignedLabel: "Assigned to",
      callCustomer: "Call customer",
      statusLabels: {
        OPEN: "Open",
        CLOSED: "Closed",
        CONVERTED: "Converted",
        NO_RESPONSE: "No response",
      },
      actions: {
        menuLabel: "Update follow-up status",
        open: "Mark as open",
        close: "Close follow-up",
        schedule: "Schedule for later",
        saving: "Saving…",
        successOpen: "Follow-up marked as open",
        successClose: "Follow-up closed",
        successSchedule: "Follow-up rescheduled",
      },
      scheduleDialog: {
        title: "Schedule follow-up",
        description: "Pick a new date for this follow-up task.",
        dateLabel: "Follow-up date",
        confirm: "Save date",
        cancel: "Cancel",
      },
    },
    calls: {
      back: "Back",
      title: "Call Users",
      subtitle: "Reconnect with customers you served to improve retention",
      scopeHint:
        "Action queues (Not answered, Follow-up calls) show pending work across the year. Month filter applies to the full customer list.",
      queuePriorityHint:
        "Not answered takes priority over follow-up call queue when both apply to the same customer.",
      yearLabel: "Year",
      monthLabel: "Month",
      monthLabels: [
        "Jan",
        "Feb",
        "Mar",
        "Apr",
        "May",
        "Jun",
        "Jul",
        "Aug",
        "Sep",
        "Oct",
        "Nov",
        "Dec",
      ],
      queueLabel: "Call queue",
      masterFilterLabel: "Source",
      segmentLabel: "Customer segment",
      valueTierLabel: "Ticket value",
      call: "Call",
      noPhone: "No phone on file",
      logManualCall: "Log manual call",
      importSpreadsheet: "Import spreadsheet",
      due: "Due",
      loadError: "Could not load customers. Sign out and sign in again, then retry.",
      loadErrorUnauthorized:
        "Your session expired or you are not signed in. Sign in again, then retry.",
      loadErrorUnavailable:
        "The server could not reach the database. Wait a moment and try again.",
      loadErrorGeneric: "Could not load customers. Please try again.",
      noCustomersYet:
        "No customers to call yet. Log a customer visit first — they will appear here.",
      previousPage: "Previous",
      nextPage: "Next",
      pageLabel: "Page {page} of {total}",
      queues: [
        { key: "ALL", label: "All customers" },
        { key: "NOT_ANSWERED", label: "Not answered" },
        { key: "FOLLOW_UP", label: "Follow-up calls" },
      ],
      masters: [
        { key: "ALL", label: "All sources" },
        { key: "STORE_VISIT", label: "Store visits" },
        { key: "FIELD_SALE", label: "Field sales" },
        { key: "EXTERNAL", label: "External" },
      ],
      segments: [
        { key: "ALL", label: "All" },
        { key: "NEW", label: "New" },
        { key: "RETAINED", label: "Retained" },
        { key: "PURCHASED", label: "Purchased" },
        { key: "NOT_PURCHASED", label: "Not purchased" },
      ],
      valueTiers: [
        { key: "ALL", label: "All values" },
        { key: "HIGH", label: "High value" },
        { key: "MID", label: "Mid value" },
        { key: "LOW", label: "Low value" },
      ],
      birthdayLabel: "Birthday",
      anniversaryLabel: "Anniversary",
      birthdays: [
        { key: "ALL", label: "All" },
        { key: "THIS_MONTH", label: "This month" },
      ],
      anniversaries: [
        { key: "ALL", label: "All" },
        { key: "THIS_MONTH", label: "This month" },
      ],
      valueTierLabels: {
        HIGH: "High value",
        MID: "Mid value",
        LOW: "Low value",
      },
      purchaseStatusLabels: {
        PURCHASED: "Purchased",
        NOT_PURCHASED: "Not purchased",
        PENDING: "Pending",
      },
      customerTypeLabels: {
        NEW: "New",
        REPEAT: "Retained",
        VIP: "VIP",
      },
      queueStatusLabels: {
        RETENTION: "Retention",
        FOLLOW_UP: "Follow-up",
        NOT_ANSWERED: "Not answered",
      },
      masterSourceLabels: {
        STORE_VISIT: "Store visit",
        FIELD_SALE: "Field sales",
        EXTERNAL: "External",
      },
      callOutcomeLabels: {
        ANSWERED: "Answered",
        NOT_ANSWERED: "Not answered",
        NOT_CALLED: "Not called yet",
      },
      notesLabel: "Notes",
      customersCount: "{count} customers",
      moreFilters: "More filters",
      hideFilters: "Hide filters",
      dialog: {
        title: "Call feedback",
        description: "Update the outcome for {name}",
        descriptionGeneric: "Update the call outcome",
        revealingPhone: "Fetching contact…",
        outcomeLabel: "Call outcome",
        answered: "Answered",
        notAnswered: "Not answered",
        feedbackLabel: "Call feedback",
        feedbackPlaceholder: "What did the customer say?",
        scheduleFollowUp: "Schedule follow-up",
        followUpDateLabel: "Follow-up date",
        notAnsweredNoteLabel: "Notes (optional)",
        notAnsweredNotePlaceholder: "Add context for the next attempt",
        notAnsweredHint: "This customer will move to your follow-up call queue.",
        saveOutcome: "Save outcome",
        saving: "Saving…",
        feedbackSaved: "Call outcome saved",
      },
      manualCall: {
        title: "Log manual call",
        description: "Record a call to someone not already in your call list.",
        nameLabel: "Customer name",
        namePlaceholder: "Enter customer name",
        phoneLabel: "Phone number",
        phonePlaceholder: "10-digit mobile number",
        phoneInvalid: "Enter a valid 10-digit phone number",
        customerTypeLabel: "Customer type",
        customerTypes: [
          { key: "NEW", label: "New" },
          { key: "REPEAT", label: "Retained" },
          { key: "VIP", label: "VIP" },
        ],
        notesLabel: "Notes (optional)",
        notesPlaceholder: "Context about the customer or call",
        saveCall: "Save call",
        saved: "Manual call logged",
      },
    },
    fieldSales: {
      back: "Back",
    },
  },
  store: {
    nav: {
      overview: "Overview",
      visits: "Visits Log",
      calls: "Call Users",
      fieldSales: "Field Sales",
      staff: "Staff",
    },
    shell: {
      title: "Store Dashboard",
    },
    ownerShell: {
      title: "Business Owner Portal",
      notifications: {
        title: "Notifications",
        subtitle:
          "Pending follow-ups, calls, and reminders for the selected store.",
        empty: "All stores are caught up right now.",
        overdue: "{count} overdue task(s)",
        dueToday: "{count} due today",
        notAnswered: "{count} not answered call(s)",
        followUpCalls: "{count} follow-up call(s)",
        openPanel: "View all notifications",
        openDashboard: "Open dashboard",
        storeFilter: {
          label: "Filter by store",
        },
      },
      nav: {
        home: "Home",
        calls: "Calls",
        followUps: "Follow-ups",
        staff: "Staff",
        activity: "Activity",
      },
      activityLog: {
        title: "Store activity",
        subtitle: "Correction requests, imports, and staff changes for the selected store.",
        loading: "Loading activity…",
        empty: "No recent activity recorded yet.",
        error: "Could not load store activity.",
        storeFilterLabel: "Filter by store",
        storeHint: "Showing activity for {store}.",
        storeFallback: "this store",
        columns: {
          time: "Time",
          event: "Event",
          actor: "By",
        },
      },
      bottomNav: {
        label: "Business owner navigation",
        home: "Home",
        calls: "Calls",
        followUps: "Follow-ups",
        more: "More",
      },
      moreSheet: {
        title: "More",
        subtitle: "Store logs, staff, and account activity",
        visitsLog: "Visits log",
        fieldSalesLog: "Field sales log",
        staff: "Staff roster",
        auditLog: "Store activity",
        analytics: "Store analytics",
      },
    },
    managerShell: {
      title: "Store Manager Portal",
      nav: {
        home: "Home",
        myCalls: "My calls",
        teamCalls: "Team calls",
        visits: "Visits",
        fieldSales: "Field sales",
        followUps: "Follow-ups",
        staff: "Staff",
        activity: "Activity",
        analytics: "Analytics",
      },
      bottomNav: {
        label: "Store manager navigation",
        home: "Home",
        myWork: "My work",
        team: "Team",
        analytics: "Analytics",
        log: "Log",
      },
      onboarding: {
        step1Title: "Welcome, store manager",
        step1Body:
          "This portal is scoped to your assigned store. Use Home for today's priorities and Team for store-wide tools.",
        step2Title: "Manage your team",
        step2Body:
          "Open Team for calls, follow-ups, visits, correction requests, and the store activity log.",
        step3Title: "Do your own RSO work",
        step3Body:
          "My work covers your personal calls, visits, and logging. You need a staff profile linked to your login — ask your business owner if it is missing.",
        step4Title: "Team tools in one place",
        step4Body:
          "Open Team for store calls, follow-ups, visits, staff roster, and correction requests.",
      },
      actorSetup: {
        title: "RSO profile not linked",
        subtitle: "Your manager account is not linked to a staff record in this store.",
        body: "Personal work — calls, visits, field sales, and your work queue — needs a staff profile on this store.",
        hint: "You can still use Team for store calls, follow-ups, visits, and correction requests.",
        viewStaffRoster: "View staff roster",
        dashboardHint: "Link your account to a staff record to unlock your personal work queue and logging.",
        stepsTitle: "What to ask your business owner",
        steps: [
          "Open Staff roster and confirm your manager staff record exists.",
          "Link your login email to that staff record.",
          "Sign out and back in, then return to My work.",
        ],
      },
      activityLog: {
        title: "Store activity",
        hubDescription: "Recent correction requests, imports, and account changes for your store.",
        cta: "View activity",
        subtitle: "Recent operational events for your store.",
        loading: "Loading activity…",
        empty: "No recent activity recorded yet.",
        error: "Could not load store activity.",
        columns: {
          time: "Time",
          event: "Event",
          actor: "By",
        },
      },
      hubs: {
        myWork: {
          title: "My work",
          subtitle: "Your personal RSO tasks, calls, and logs.",
        },
        team: {
          title: "Team",
          subtitle: "Monitor and manage your store team's activity.",
        },
      },
      notifications: {
        title: "Notifications",
        empty: "No pending items today.",
        unlinked: "Link your staff profile to see personal notifications.",
        overdue: "{count} overdue task(s)",
        dueToday: "{count} due today",
        openHome: "Open dashboard",
      },
      logSheet: {
        title: "Log activity",
        subtitle: "Record your own visits and field sales",
        logVisit: "Log customer visit",
        logFieldSale: "Log field sale",
      },
      moreSheet: {
        title: "More",
        subtitle: "Personal work and store management",
        personalSection: "My work",
        teamSection: "Team",
        myVisits: "My visits",
        myFieldSales: "My field sales",
        myFollowUps: "My follow-ups",
        teamFollowUps: "Store follow-ups",
        correctionRequests: "Correction requests",
        activityLog: "Store activity",
        visitsLog: "Store visits log",
        fieldSalesLog: "Store field sales log",
        staff: "Staff roster",
        analytics: "Store analytics",
      },
    },
    ownerDashboard: {
      title: "Business owner dashboard",
      subtitle:
        "Track store performance, pending tasks, and team activity across your portfolio.",
      guide:
        "Review KPIs by store, spot overdue work, and drill into calls, follow-ups, and staff performance.",
      workQueue: {
        title: "Store work queue",
        subtitle: "Pending follow-ups, missed calls, and reminders across your portfolio.",
        empty: "All stores are caught up right now.",
        previewHint: "Showing {shown} of {total} pending items.",
        viewFollowUps: "Open follow-ups",
        viewCalls: "Open team calls",
        viewAllCategory: "View all {count} in follow-ups",
        browseSelectPrompt: "Select a category above to review pending items.",
        browseEmpty: "No preview items in this category. Use the store links below.",
        browseCategoryHint: "{count} pending item(s)",
        storeFilter: {
          label: "Filter by store",
          allStores: "All stores",
        },
        storeSummary: "{store}: {count} pending",
        sections: {
          mismatchedAssignment: "Needs reassignment",
        },
        oversight: {
          storeLabel: "Store",
          assigneeLabel: "Assigned to",
          dueLabel: "Due",
          reviewItem: "Review",
        },
      },
      teamWorkload: {
        title: "Urgent team workload",
        subtitle: "Staff with pending, overdue, or due-today work across your stores.",
        empty: "All teams are caught up right now.",
        pending: "{count} pending",
        overdue: "{count} overdue",
        dueToday: "{count} due today",
        viewCalls: "Calls",
        viewFollowUps: "Follow-ups",
      },
      teamActivity: {
        title: "Team activity",
        subtitle: "Pending tasks and performance by staff member across your stores.",
        empty: "No active staff in your portfolio yet.",
        viewStaff: "View staff roster",
        viewCalls: "Calls",
        viewFollowUps: "Follow-ups",
        overdueHint: "{count} overdue",
        dueTodayHint: "{count} due today",
        statusNeedsAttention: "Needs attention",
        statusOnTrack: "On track",
        columns: {
          store: "Store",
          staff: "Staff",
          visits: "Visits",
          conversion: "Conversion",
          openFollowUps: "Open follow-ups",
          pendingWork: "Pending work",
          status: "Status",
          actions: "Actions",
        },
      },
      actions: {
        teamSectionTitle: "Manage your stores",
        teamSectionSubtitle:
          "Team-wide logs, follow-ups, staff roster, and store analytics.",
        teamCalls: {
          title: "Team Calls",
          description: "Store-wide call queues — track outcomes across stores",
          cta: "Open team calls",
        },
        visitsLog: {
          title: "Visit Log",
          description: "All store visits — review activity and reassign customers",
          cta: "View visit log",
        },
        fieldSalesLog: {
          title: "Field Sales Log",
          description: "Outdoor activity and enrollments across your stores",
          cta: "View field sales",
        },
        followUps: {
          title: "Follow-ups",
          description: "Open follow-up tasks — review assignments across stores",
          cta: "View follow-ups",
        },
        staffRoster: {
          title: "Staff Roster",
          description: "RSO performance, open follow-ups, and workload",
          cta: "View staff",
        },
        auditLog: {
          title: "Audit Log",
          description: "Recent imports, staff changes, and account activity",
          cta: "View audit log",
        },
        storeAnalytics: {
          title: "Store Analytics",
          description: "KPIs, call performance, and RSO leaderboard for a store",
          cta: "Open analytics",
        },
      },
    },
    managerDashboard: {
      title: "Store manager dashboard",
      subtitle: "Track your team, assign customers, and complete your own RSO work.",
      personalWorkQueue: {
        title: "Your work queue",
        subtitle: "Your overdue calls, follow-ups, and reminders for today.",
      },
      storeWorkQueue: {
        title: "Store work queue",
        subtitle: "Pending follow-ups, missed calls, and reminders across your store.",
        empty: "Your store is caught up right now.",
        previewHint: "Showing {shown} of {total} pending items.",
      },
      homeQueues: {
        tabListLabel: "Work queue view",
        storeTab: "Store tasks",
        personalTab: "Your tasks",
        hubTabListLabel: "Tools view",
        teamHubTab: "Team",
        myWorkHubTab: "My work",
      },
      assignment: {
        title: "Store workload",
        subtitle: "Open follow-ups and staffing across your store.",
        customersWithOpenWork: "Customers with open work",
        customersWithOpenWorkHint: "Unique customers with at least one open follow-up.",
        openFollowUps: "Open follow-ups",
        openFollowUpsHint: "All open follow-up tasks in this store.",
        mismatchedAssignments: "Needs reassignment",
        mismatchedAssignmentsHint: "Follow-ups where the owner and assignee differ.",
        activeStaff: "Active staff",
        activeStaffHint: "RSOs and managers active in this store.",
      },
      teamWorkload: {
        title: "Team workload today",
        subtitle: "Staff with pending, overdue, or due-today work.",
        empty: "Everyone is caught up right now.",
        pending: "{count} pending",
        overdue: "{count} overdue",
        dueToday: "{count} due today",
        viewCalls: "Calls",
        viewFollowUps: "Follow-ups",
      },
      followUps: {
        personal: {
          title: "My follow-up tasks",
          subtitle: "Scheduled tasks from your visits and field sales",
          guide: "Personal tasks assigned to you as an RSO.",
          empty: "No overdue follow-ups right now.",
          emptyDueToday: "No follow-ups due today.",
          emptyOpen: "No open follow-ups right now.",
          filters: {
            overdue: "Overdue",
            due_today: "Due today",
            open: "All open",
          },
        },
        store: {
          title: "Store follow-up tasks",
          subtitle: "All open follow-ups across your store",
          cta: "View follow-ups",
          guide: "Reassign tasks when the owner and assignee do not match.",
          empty: "No overdue follow-ups right now.",
          emptyDueToday: "No follow-ups due today.",
          emptyOpen: "No open follow-ups right now.",
          emptyMismatched: "No mismatched assignments right now.",
          filters: {
            overdue: "Overdue",
            due_today: "Due today",
            open: "All open",
            mismatched: "Needs reassignment",
          },
          bulkReassign: {
            selectAll: "Select all on page",
            selected: "{count} selected",
            assignTo: "Assign to",
            submit: "Reassign selected",
            submitting: "Reassigning…",
            success: "Reassigned {count} follow-up(s).",
            noneSelected: "Select follow-ups to reassign.",
          },
        },
      },
      teamActivity: {
        title: "RSO & staff activity",
        subtitle: "Pending tasks and call reminders by team member.",
        empty: "No active staff in this store yet.",
        viewStaff: "View staff roster",
        viewCalls: "Calls",
        viewFollowUps: "Follow-ups",
        overdueHint: "{count} overdue",
        dueTodayHint: "{count} due today",
        statusNeedsAttention: "Needs attention",
        statusOnTrack: "On track",
        columns: {
          staff: "Staff",
          visits: "Visits",
          conversion: "Conversion",
          openFollowUps: "Open follow-ups",
          pendingWork: "Pending work",
          status: "Status",
          actions: "Actions",
        },
      },
      actions: {
        personalSectionTitle: "Your work as RSO",
        personalSectionSubtitle: "Same tools your staff use for visits, calls, and field sales.",
        teamSectionTitle: "Manage your store",
        teamSectionSubtitle: "Team-wide logs, assignments, performance, and store analytics.",
        tabPersonal: "As RSO",
        tabTeam: "Manage store",
        personal: {
          logVisit: {
            title: "Log Customer Visit",
            description: "Record walk-in or appointment details",
            cta: "Log visit",
          },
          myVisits: {
            title: "My Visits",
            description: "Review visits you logged and request corrections",
            cta: "View my visits",
          },
          callUsers: {
            title: "My Calls",
            description: "Your personal call queue and retention outcomes",
            cta: "Open my calls",
          },
          fieldSales: {
            title: "Log Field Sale",
            description: "Record outdoor visits and GHS / JPP enrollments",
            cta: "Log field sale",
          },
          myFieldSales: {
            title: "My Field Sales",
            description: "Review field sales you logged",
            cta: "View my field sales",
          },
          followUps: {
            title: "My follow-ups",
            description: "Your scheduled tasks from visits and field sales",
            cta: "View my follow-ups",
          },
        },
        team: {
          teamCalls: {
            title: "Team Calls",
            description: "Store-wide call queue — assign and track outcomes",
            cta: "Open team calls",
          },
          visitsLog: {
            title: "Visit Log",
            description: "All store visits — reassign customers to staff",
            cta: "View visit log",
          },
          fieldSalesLog: {
            title: "Field Sales Log",
            description: "All outdoor activity — reassign as needed",
            cta: "View field sales",
          },
          staffRoster: {
            title: "Staff Roster",
            description: "RSO performance, open follow-ups, and workload",
            cta: "View staff",
          },
          storeDashboard: {
            title: "Store Analytics",
            description: "KPIs, call performance, and RSO leaderboard",
            cta: "Open analytics",
          },
        },
      },
    },
    managerPortal: {
      title: "What would you like to do?",
      subtitle: "Choose an action to get started",
      actions: {
        logVisit: {
          title: "Log Customer Visit",
          description: "Record walk-in or appointment details for store analytics",
          cta: "Log visit",
        },
        callUsers: {
          title: "Call Users",
          description: "Call customers you served and log retention outcomes",
          cta: "View call list",
        },
        fieldSales: {
          title: "Field Sales",
          description: "Log outdoor visits and GHS / JPP enrollments in the field",
          cta: "Log field sale",
        },
        storeDashboard: {
          title: "Store analytics",
          description: "Open KPIs, analytics, and performance for your store",
          cta: "Open analytics",
        },
      },
    },
    correctionRequests: {
      title: "Correction requests",
      subtitle: "Staff requests to fix records they can no longer edit",
      empty: "No open correction requests.",
      resolve: "Mark resolved",
      resolving: "Resolving…",
      viewRecord: "View record",
      visitRecord: "Visit",
      fieldSaleRecord: "Field sale",
      unknownCustomer: "Unknown customer",
    },
    kpis: {
      totalVisits: "Total Visits",
      totalRevenue: "Total Revenue",
      conversionRate: "Conversion Rate",
      avgTransaction: "Avg Transaction",
      newCustomers: "New Customers",
      repeatCustomers: "Repeat Customers",
      schemesEnrolled: "Schemes Enrolled",
      openFollowUps: "Open Follow-ups",
    },
    period: {
      yesterday: "Yesterday",
      today: "Today",
      week: "This Week",
      month: "This Month",
      last3months: "Last 3 Months",
      last6months: "Last 6 Months",
    },
    deltaPeriod: "vs last period",
    storeSelector: {
      label: "Store",
      placeholder: "Select store",
      loading: "Loading stores…",
    },
    portfolio: {
      title: "Your Stores",
      subtitle:
        "Visits, revenue, and conversion for each store in the selected period.",
      viewOnlyBadge: "View only",
      viewDetails: "Open store dashboard",
      emptyStores: "No stores are linked to your account yet.",
      selectStorePrompt:
        "Choose a store from the portfolio overview before viewing this section.",
      backToStores: "View all stores",
      active: "Active",
      inactive: "Inactive",
      staffCount: "Staff",
      fieldSales: "Field sales",
      userCalls: "User calls",
      avgTicketSize: "Average ticket size",
      schemesEnrolled: "Schemes enrolled",
      storeManager: "Store manager",
      storeManagerPhone: "Store manager phone",
      notAvailable: "—",
    },
    storeDetail: {
      backToPortfolio: "All stores",
      backToPortal: "Back to dashboard",
      titleFallback: "Store dashboard",
      locationHint: "Store location on file",
      viewOverview: "Overview",
      storeSectionNavLabel: "Store sections",
      viewVisits: "Visits log",
      viewCalls: "Call users",
      viewFieldSales: "Field sales",
      viewStaff: "Staff",
      viewAudit: "Activity log",
    },
    businessOverview: {
      title: "Business Overview ({period})",
      subtitle:
        "Store-wide visits, revenue, conversion, and customer metrics at a glance.",
      purchasedVisits: "Purchased visits",
      notPurchasedVisits: "Non-purchased visits",
    },
    callsOverview: {
      title: "Call Users Overview ({period})",
      subtitle:
        "Track outbound follow-up calls, answer rates, staff effort, and note themes to improve retention.",
      empty: "No call activity recorded for this period",
      error: "Unable to load call analytics.",
      retry: "Retry",
      tabs: {
        overview: "Overview",
        segments: "Segments",
        team: "Team",
        notes: "Notes",
      },
      kpis: {
        totalCalls: "Total Calls",
        answered: "Answered",
        notAnswered: "Not Answered",
        answerRate: "Answer Rate",
        coverage: "Pool Coverage",
        callToConversion: "Call → Conversion",
        feedbackRate: "Notes Logged",
        activeStaff: "Active Callers",
        avgCallsPerStaff: "Avg Calls / Staff",
        storeVisitsFromCalls: "Store Visits (User Calls)",
        storeVisitsFromCallsConversion: "User Calls → Purchase",
      },
      highlights: {
        bestAnswerRate: "Best Answer Rate",
        needsAttention: "Needs Coaching",
      },
      charts: {
        staffVolume: "Calls per Staff",
        staffVolumeHint: "Who is driving follow-up volume",
        staffOutcome: "Staff Outcomes",
        staffOutcomeHint: "Answered vs unanswered by team member",
        byCustomerType: "By Customer Type",
        byPurchaseStatus: "By purchase status (calls)",
        visitLogByPurchaseStatus: "Visit log outcomes",
        visitLogByPurchaseStatusHint: "Purchased vs non-purchased from RSO visit logs",
        byValueTier: "By Value Tier",
        byIntent: "By Intent Tier",
      },
      notes: {
        title: "Call Notes & Themes",
        subtitle:
          "Keyword themes from staff feedback; AI summary when Gemini API key is configured.",
        aiSummary: "AI summary",
        aiUnavailable:
          "Add GEMINI_API_KEY to .env.local for AI-generated call notes summary.",
        aiPending: "Not enough notes for an AI summary yet.",
        themes: "Common themes in notes",
        recentNotes: "Recent call notes",
      },
      table: {
        title: "Staff Call Breakdown",
        staff: "Staff",
        totalCalls: "Calls",
        answered: "Answered",
        notAnswered: "Unanswered",
        answerRate: "Answer %",
        callToConversion: "Call → Conv.",
        uniqueVisits: "Visits",
        feedback: "With notes",
      },
      viewInLog: "View in Call Users log",
      viewInLogHint: "Click a chart bar or staff row to open matching call records",
      exportCsv: "Export CSV",
    },
    fieldSalesOverview: {
      title: "Field Sales Overview ({period})",
      subtitle:
        "Track outdoor visits, areas covered, follow-ups, and enrollments to grow GHS/JPP business.",
      empty: "No field sales activity recorded for this period",
      error: "Unable to load field sales analytics.",
      retry: "Retry",
      tabs: {
        overview: "Overview",
        segments: "Segments",
        team: "Team",
        notes: "Notes",
      },
      kpis: {
        totalVisits: "People Visited",
        enrollmentRate: "Enrollment Rate",
        enrolled: "Enrolled",
        uniqueAreas: "Areas Covered",
        followUpRequired: "Follow-ups Required",
        followUpConversion: "Follow-up → Enrolled",
        interested: "Interested / Callback",
        declined: "Declined",
      },
      insights: {
        sectionTitle: "Field performance insights",
        sectionSubtitle:
          "Channel conversion, coaching signals, follow-up closure, and note themes to guide field strategy.",
        enrollmentByActivity: "Enrollment rate by activity type",
        enrollmentByActivityHint:
          "Compare housing society vs door-to-door and other channels — double down on high converters.",
        declineReasons: "Decline reasons (coaching)",
        declineReasonsHint:
          "Budget, trust, and competitor objections — use for coaching, offers, and rebuttals.",
        followUpConversion: "Follow-up → enrolled",
        followUpConversionHint:
          "Measures whether callbacks close — enrolled after a follow-up was required.",
        followUpConverted: "{converted} enrolled of {required} follow-ups required",
        intentTier: "Enrollment by intent tier",
        intentTierHint: "Prioritize hot leads in the field — spot where intent converts.",
        notesThemes: "Notes themes",
        notesThemesHint:
          "Objections and interest signals from staff notes (budget, trust, competitor, scheme interest).",
        noDeclineData: "No decline reasons recorded yet.",
        noNotesThemes: "No note themes yet — ask staff to log objections and interest in notes.",
      },
      highlights: {
        bestEnrollmentRate: "Best Enrollment Rate",
        needsAttention: "Needs Coaching",
      },
      charts: {
        outcomeSplit: "Enrollment Outcomes",
        outcomeSplitHint: "Enrolled vs pipeline vs lost for the period",
        dailyVolume: "Daily Field Activity",
        dailyVolumeHint: "Visits and enrollments by day",
        enrollmentTrend: "Daily Enrollment Rate",
        enrollmentTrendHint: "Spot days with stronger scheme conversion",
        byActivityType: "By Activity Type",
        byOutcome: "By Enrollment Outcome",
        byArea: "Top Areas Covered",
        byCustomerType: "By Customer Type",
        byIntent: "By Intent Tier",
        byDeclineReason: "Decline Reasons",
        followUpStatus: "Follow-up Status",
        followUpStatusHint: "Open, converted, and closed follow-ups from field visits",
        staffVolume: "Visits per Staff",
        staffVolumeHint: "Who is covering the most ground",
        staffOutcome: "Staff Enrollments",
        staffOutcomeHint: "Enrolled vs not enrolled by team member",
        segmentClickHint: "Click a bar to view matching field sales records",
      },
      notes: {
        title: "Field Notes & Themes",
        subtitle:
          "Keyword themes from staff notes; AI summary when Gemini API key is configured.",
        aiSummary: "AI summary",
        aiUnavailable:
          "Add GEMINI_API_KEY to .env.local for AI-generated field notes summary.",
        aiPending: "Not enough notes for an AI summary yet.",
        themes: "Common themes in notes",
        recentNotes: "Recent field notes",
      },
      table: {
        title: "Staff Field Sales Breakdown",
        staff: "Staff",
        totalVisits: "Visits",
        enrolled: "Enrolled",
        enrollmentRate: "Enroll %",
        followUpNeeded: "Follow-ups",
        followUpsConverted: "Converted",
        uniqueAreas: "Areas",
        notes: "With notes",
      },
      viewInLog: "View in Field Sales log",
      viewInLogHint: "Click a chart bar or staff row to open matching field records",
      exportCsv: "Export CSV",
    },
    rsoPerformance: {
      title: "RSO Revenue Performance ({period})",
      subtitle:
        "Compare RSO sales, conversion, scheme enrollments, and revenue growth for the store.",
      empty: "No RSO performance data for this period",
      error: "Unable to load RSO performance.",
      retry: "Retry",
      emptyHighlight: "Not enough data yet",
      highlights: {
        topPerformer: {
          title: "Top Performer",
        },
        mostImproved: {
          title: "Most Improved",
        },
      },
      charts: {
        staffRevenue: "Revenue by RSO",
        staffRevenueHint: "Who is driving the most revenue this period",
        staffConversion: "RSO Conversion Rate",
        staffConversionHint: "Purchase conversion by team member",
      },
      table: {
        title: "RSO Performance Breakdown",
        staff: "RSO Name",
        customersAttended: "Customers Attended",
        purchased: "Purchased",
        notPurchased: "Non Purchased",
        schemesEnrolled: "Schemes Enrolled",
        dataEntryScore: "DES score",
        growth: "Growth",
        revenue: "Revenue",
      },
      exportCsv: "Export CSV",
      columns: {
        rsoName: "RSO Name",
        customersAttended: "Customers Attended",
        purchased: "Purchased",
        notPurchased: "Non Purchased",
        schemesEnrolled: "Schemes Enrolled",
        dataEntryScore: "DES score",
        growth: "Growth",
        revenue: "Revenue",
      },
      topPerformer: {
        title: "Top Performer",
      },
      mostImproved: {
        title: "Most Improved",
      },
    },
    table: {
      showing: "Showing {from}–{to} of {total}",
      page: "Page {page}",
      yes: "Yes",
    },
    visits: {
      title: "Visits Log",
      viewOnlySubtitle: "View only — store staff and managers log new visits from their portal.",
      searchPlaceholder: "Customer name, phone, or staff name",
      filters: {
        all: "All Visits",
        followUpOnly: "Follow-up Only",
        startDate: "From Date",
        endDate: "To Date",
        clearDate: "Clear date",
        invalidDateRange: "End date must be on or after start date.",
        dateRangeHint: "Leave dates empty to show all visits, or pick a from/to range.",
        columnAll: "All",
        clearColumnFilters: "Clear column filters",
      },
      columns: {
        visitId: "Visit ID",
        date: "Date",
        inTime: "In Time",
        outTime: "Out Time",
        duration: "Duration",
        staff: "Staff",
        customer: "Customer",
        phone: "Phone",
        customerType: "Customer Type",
        type: "Visit Type",
        sourceChannel: "Source / Channel",
        area: "Area / Locality",
        gender: "Gender",
        ageGroup: "Age Group",
        status: "Purchase Status",
        productsExplored: "Products Explored",
        productsPurchased: "Products Purchased",
        revenue: "Revenue",
        intentTier: "Intent Tier",
        reasonNoPurchase: "Reason No Purchase",
        competitorMention: "Competitor Mention",
        purchaseOccasion: "Purchase Occasion",
        metalKtPref: "Metal / KT Preference",
        budgetStated: "Budget Stated",
        schemeEnrolled: "Scheme Enrolled",
        ghsPolicy: "GHS Policy",
        followUp: "Follow-up Needed",
        followUpDate: "Follow-up Date",
        followUpStatus: "Follow-up Status",
        notes: "Staff Notes",
        products: "Products",
      },
      detailTitle: "Visit Details",
      importCsv: "Import CSV",
      importSpreadsheet: "Import spreadsheet",
      importingCsv: "Importing...",
      importHint:
        "Upload a CSV with visit fields. Data is validated and saved to your store database.",
      importSuccess: "Imported {count} rows successfully.",
      importPartial: "Imported {created} rows. {failed} rows failed validation.",
      importFailed: "CSV import failed. Check your file and try again.",
      sections: {
        customer: "Customer Details",
        visit: "Visit Details",
        noPurchase: "No-Purchase Context",
        preferences: "Preferences & Schemes",
        followUp: "Follow-up",
      },
      customerProfile: {
        title: "Customer Profile",
        subtitle: "Timeline, interests, and behaviour across every touchpoint",
        phone: "Phone",
        area: "Area",
        demographics: "Demographics",
        memberSince: "Customer since",
        lastSeen: "Last seen",
        ghsEnrolled: "GHS enrolled",
        taggedAtVisit: "Tagged at latest visit",
        visitsOnRecord: "{count} visits on record",
        loadError: "Could not load customer profile. Try again.",
        interestsTitle: "Interests & preferences",
        insightsTitle: "Behaviour insights",
        timelineTitle: "Customer journey",
        timelineEmpty: "No activity recorded yet for this customer.",
        viewVisit: "View visit",
        stats: {
          visits: "Store visits",
          revenue: "Lifetime revenue",
          conversion: "Conversion",
          fieldSales: "Field activities",
        },
        interests: {
          explored: "Products explored",
          purchased: "Products purchased",
          metal: "Metal / KT preference",
          occasions: "Purchase occasions",
          intent: "Intent signals",
          sources: "How they found you",
        },
        insights: {
          staff: "Staff relationships",
          interactions: "touchpoints",
          competitors: "Competitor mentions",
          noPurchase: "Reasons for no purchase",
        },
      },
    },
    staff: {
      title: "Staff Management",
      addStaff: "Add Staff",
      accountCreated:
        "Staff account created. Share their work email and password so they can sign in.",
      inviteSent: "Invitation email sent. They will set their own password.",
      columns: {
        name: "Name",
        employeeId: "Employee ID",
        role: "Role",
        phone: "Phone",
        email: "Email",
        createdAt: "Created",
        visits: "Visits",
        revenue: "Revenue",
        conversionRate: "Conversion Rate",
        status: "Status",
        actions: "Actions",
      },
      managerColumns: {
        openFollowUps: "Open follow-ups",
        pendingWork: "Pending work",
      },
      roles: {
        STORE_MANAGER: "Store manager",
        STAFF: "RSO",
      },
      actions: {
        menu: "Staff actions",
        edit: "Edit staff details",
        markActive: "Mark as active",
        markInactive: "Mark as inactive",
        delete: "Delete staff",
        deleteBlocked: "Cannot delete staff with logged visits or follow-ups",
      },
      updated: "Staff details updated",
      deleteConfirm: {
        title: "Delete staff member?",
        description:
          "This permanently removes {name} and revokes their login access. This cannot be undone.",
        confirm: "Delete",
        cancel: "Cancel",
      },
      statusUpdated: "Staff status updated",
      deleted: "Staff member deleted",
      importCsv: "Import CSV",
      importResult: "Imported {created} staff ({failed} failed)",
      readOnlyHint: "View-only roster — contact the business owner to manage staff.",
      modal: {
        title: "Add Staff Member",
        nameLabel: "Name",
        emailLabel: "Work email",
        employeeIdLabel: "Employee ID",
        roleLabel: "Role",
        rolePlaceholder: "Select role",
        phoneLabel: "Phone number",
        phonePlaceholder: "10-digit mobile",
        passwordLabel: "Password",
        passwordPlaceholder: "Initial sign-in password",
        suggestPassword: "Suggest password",
        passwordHint:
          "Stored securely in auth. Staff sign in at the home page with their work email and this password.",
      },
      editModal: {
        title: "Edit staff details",
        save: "Save changes",
      },
      active: "Active",
      inactive: "Inactive",
    },
  },
  admin: {
    nav: {
      overview: "Portfolio",
      analytics: "Analytics",
      stores: "Stores",
      audit: "Audit",
    },
    analytics: {
      title: "AI Analytics",
      storeFilterLabel: "Store",
      allStoresLabel: "All stores",
      emptyBreakdown: "No breakdown data for this period.",
      kpis: {
        visits: "Visits",
        revenue: "Revenue",
        conversion: "Conversion rate",
        avgTransaction: "Avg. transaction",
        fieldSales: "Field sales",
        uniqueCustomers: "Unique customers",
      },
      ask: {
        title: "AI analytics",
        chatPanelIntro:
          "Ask questions in plain language. Charts, metrics, and recommendations are computed from your live store data on the server.",
        historyTabLabel: "History",
        historyEmpty: "Your recent questions will appear here.",
        promptLabel: "Your question",
        promptPlaceholder:
          "e.g. Compare this month vs last year revenue by customer type for high value new customers",
        analyzeButton: "Analyze",
        chatEmptyTitle: "Start a conversation",
        chatEmptyDescription:
          "Ask about revenue, visits, segments, or trends. Your answer appears here with charts and a report.",
        examplesLabel: "AI recommendations",
        examplePrompts: [
          {
            id: "compare",
            hint: "Period comparison",
            template: "Compare {currentPeriod} vs {priorYearPeriod} revenue",
          },
          {
            id: "compare-visits",
            hint: "Year over year",
            template: "Compare {currentPeriod} vs {priorYearPeriod} visits and conversion",
          },
          {
            id: "trend",
            hint: "Trend",
            template: "Last 30 days revenue trend by visit source",
          },
          {
            id: "week",
            hint: "Recent",
            template: "Last 7 days visits by customer type",
          },
          {
            id: "segment",
            hint: "Segment",
            template: "High value new customers last 90 days by product category",
          },
          {
            id: "breakdown",
            hint: "Breakdown",
            template: "{currentPeriod} visits and conversion breakdown by intent tier",
          },
          {
            id: "conversion",
            hint: "Conversion",
            template: "{currentPeriod} conversion and purchase status breakdown",
          },
          {
            id: "source",
            hint: "Channels",
            template: "Last 30 days visits by source channel for repeat customers",
          },
          {
            id: "area",
            hint: "Location",
            template: "{currentPeriod} revenue breakdown by area",
          },
          {
            id: "vip",
            hint: "VIP",
            template: "VIP customers last 90 days by product category",
          },
          {
            id: "scheme",
            hint: "Schemes",
            template: "Last 90 days scheme enrollment breakdown by enrollment outcome",
          },
          {
            id: "retained",
            hint: "Retention",
            template: "Retained customers last 6 months by customer type",
          },
          {
            id: "overview",
            hint: "Overview",
            template: "Last 30 days performance snapshot and revenue trend",
          },
        ],
        interpretedLabel: "We understood",
        aiPowered: "Analysis enhanced with Gemini.",
        rulePowered: "Analysis from server rules on your live data.",
        geminiNotConfigured: "Gemini key not set — using rule-based parser",
        reportTitle: "Analysis report",
        highlightsTitle: "Key insights",
        recommendationsTitle: "Recommendations",
      },
    },
    shell: {
      title: "Consultant Admin",
    },
    overview: {
      title: "Client Store Portfolio",
      subtitle: "Each store is tracked separately — no combined chain metrics.",
      totalStores: "Total Stores",
      activeStores: "Active Stores",
      listedStores: "Showing Stores",
      allCategories: "All categories",
      viewDetails: "View analytics",
      actions: "Actions",
      emptyStores: "No stores match the selected filters.",
    },
    categories: {
      JEWELRY: "Jewelry",
      HANDBAGS: "Handbags",
      WATCHES: "Watches",
      OTHER: "Other",
    },
    storeDetail: {
      backToPortfolio: "All stores",
      notFound: "Store not found.",
      titleFallback: "Store dashboard",
      storeSectionNavLabel: "Store sections",
      viewOverview: "Overview",
      viewVisits: "Visits log",
      viewCalls: "Call users",
      viewFieldSales: "Field sales",
      viewStaff: "Staff",
      revenueTrend: "Revenue trend",
      sourceBreakdown: "Visit sources",
      purchaseStatusBreakdown: "Purchase outcomes",
      noPurchaseReasons: "Reasons for no purchase",
      noBreakdownData: "No visit data for this period.",
    },
    kpis: {
      totalRevenue: "Revenue",
      totalVisits: "Visits",
      conversionRate: "Conversion Rate",
      activeStores: "Active Stores",
      totalStaff: "Staff",
      fieldSales: "Field sales",
      userCalls: "User calls",
      avgTicketSize: "Average ticket size",
      schemesEnrolled: "Schemes enrolled",
      storeManager: "Store manager",
      storeManagerPhone: "Store manager phone",
      notAvailable: "—",
    },
    stores: {
      title: "Stores Management",
      addStore: "Add Store",
      columns: {
        name: "Store Name",
        category: "Category",
        city: "City",
        pincode: "Pincode",
        businessOwnerName: "Business owner",
        businessOwnerEmail: "Business owner email",
        staffCount: "Staff Count",
        revenue: "Revenue",
        status: "Status",
        actions: "Actions",
      },
      actions: {
        menu: "Store actions",
        edit: "Edit store",
        makeInactive: "Make inactive",
        makeActive: "Make active",
        updatePassword: "Update password",
        restore: "Restore store",
        delete: "Delete store",
      },
      inactiveConfirm: {
        title: "Make store inactive?",
        description:
          "{name} will be hidden from active lists. Staff and data remain until you reactivate or delete the store.",
        confirm: "Make inactive",
        cancel: "Cancel",
      },
      activeConfirm: {
        title: "Make store active?",
        description: "{name} will appear in active store lists again.",
        confirm: "Make active",
        cancel: "Cancel",
      },
      deleteConfirm: {
        title: "Delete store?",
        description:
          "{name} will be removed from the admin list immediately. Store managers, staff, visits, and customers stay in the database for 90 days so you can restore the store if needed.",
        confirm: "Delete store",
        cancel: "Cancel",
        adminPasswordLabel: "Your admin password",
        adminPasswordPlaceholder: "Enter your password",
        storeNameLabel: "Type store name to confirm",
        storeNamePlaceholder: "Exact store name",
        storeNameMismatch: "Store name does not match.",
        wrongPassword: "Incorrect admin password.",
        graceNote:
          "Recovery window: 90 days. Contact support or use restore API before permanent purge.",
      },
      deleteBlocked:
        "Could not delete this store. Try again or deactivate the store instead.",
      passwordModal: {
        title: "Update store password",
        description:
          "Sets a new sign-in password for the store manager account linked to {name}.",
        confirm: "Update password",
        cancel: "Cancel",
      },
      passwordUpdated: "Store manager password updated",
      statusUpdated: "Store status updated",
      deleted: "Store removed (recoverable for 90 days)",
      restored: "Store restored",
      updated: "Store updated",
      purgeCountdown: "Purges in {days} days",
      ownershipTransfer: {
        title: "Transfer business owner login?",
        description:
          "Changing the business owner email updates the manager login for this store. The new email must not already belong to another user.",
        confirm: "Update owner email",
      },
      modal: {
        title: "Add Store",
        nameLabel: "Store Name",
        namePlaceholder: "Enter store name",
        categoryLabel: "Store Category",
        cityLabel: "City",
        cityPlaceholder: "Enter city",
        stateLabel: "State",
        statePlaceholder: "Enter state",
        pincodeLabel: "Store pincode",
        pincodePlaceholder: "6-digit pincode",
        customCategoryLabel: "Custom Category",
        customCategoryPlaceholder: "Enter category name",
        businessOwnerNameLabel: "Business owner name",
        businessOwnerNamePlaceholder: "Full name of business owner",
        businessOwnerEmailLabel: "Business owner email",
        businessOwnerEmailPlaceholder: "owner@store.example",
        passwordLabel: "Store password",
        passwordPlaceholder: "Initial sign-in password",
        suggestPassword: "Suggest password",
        passwordHint:
          "Manager signs in at the home page with the business owner email and this password. Requires business owner email.",
        existingManagerHint:
          "This business owner email already has a manager login. The new store will appear in their store list — no new password needed.",
        linkedExistingManagerDescription:
          "Store added. The manager can sign in with their existing password and switch stores from the overview dropdown.",
        createSuccessTitle: "Store created",
        createSuccessDescription:
          "Share these login details with the store manager. They sign in at the store portal.",
      },
      editModal: {
        title: "Edit store",
        save: "Save changes",
      },
    },
    staff: {
      title: "Staff Analytics",
      leaderboard: "Top Performers",
      allStores: "All Stores",
      columns: {
        name: "Staff Name",
        store: "Store",
        visits: "Visits",
        revenue: "Revenue",
        conversionRate: "Conversion Rate",
        followUpRate: "Follow-up Rate",
      },
    },
    period: {
      yesterday: "Yesterday",
      today: "Today",
      week: "This Week",
      month: "This Month",
      last3months: "Last 3 Months",
      last6months: "Last 6 Months",
    },
    deltaPeriod: "vs last period",
    table: {
      active: "Active",
      inactive: "Inactive",
    },
  },
  errors: {
    generic: "Something went wrong. Please try again.",
    boundaryTitle: "Something went wrong",
    tryAgain: "Try again",
    unauthorized: "You are not authorised to view this page.",
    notFound: "The requested resource was not found.",
    validation: "Please check the highlighted fields.",
    rateLimited: "Too many requests. Please try again later.",
  },
  empty: {
    visits: "No visits recorded yet",
    followUps: "No follow-ups to show",
    staffCalls: "No customers match these filters",
    portalCalls: "No call activity matches these filters",
    fieldSales: "No field sales match these filters",
    staff: "No staff members found",
    stores: "No stores found",
  },
  import: {
    upload: {
      sheetsTitle: "Choose sheets to import",
      sheetsHint:
        "This workbook has multiple tabs. Select which ones to include — rows from each tab are combined into one import.",
      sheetRows: "{count} rows",
      selectAll: "Select all",
      deselectAll: "Deselect all",
      continue: "Continue with selected sheets",
      noSheetsSelected: "Select at least one sheet to continue.",
    },
    mapping: {
      summary: "{autoMapped} of {total} columns mapped automatically · {needsReview} need review",
      tableHint:
        "Check that each spreadsheet column maps to the right store field. The preview shows real values from the first rows of your file.",
      columns: {
        uploadedHeader: "Column in your file",
        preview: "Preview from file",
        previewHint: "First 3 values",
        mappedTo: "Maps to store field",
        confidence: "Match quality",
        action: "How mapped",
      },
      previewEmpty: "Empty in file",
      previewPrefix: "e.g.",
      actionAuto: "Auto",
      actionManual: "You chose",
      callLogDefaults:
        "Call date and agent name are optional — if missing, we use today’s date and the staff member running the import.",
    },
    confirm: {
      severityTitle: "Understanding row status",
      severityIntro:
        "Every row is checked before import. Some issues block a row entirely; others import with missing or corrected fields.",
      errorSeverityTitle: "Error rows — will not import",
      errorSeverityBody:
        "{count} row(s) have blocking problems (e.g. invalid phone). Fix them in your spreadsheet and re-upload, or proceed without these rows.",
      warningSeverityTitle: "Warning rows — will import with gaps",
      warningSeverityBody:
        "{count} row(s) will import, but some fields could not be matched or parsed and will be left empty (e.g. staff name not found).",
      validSeverityTitle: "Valid rows — ready to import",
      validSeverityBody: "{count} row(s) passed all checks with no issues.",
      importCountNote: "Starting import will add {count} row(s): valid + warning rows.",
      blockingIssues: "Blocking issues ({count} rows affected)",
      reviewIssues: "Items to review ({count} rows affected)",
      howToFix: "How to fix",
      willNotImport: "Will not import",
      willImport: "Will still import",
      rowCount: "{count} rows",
      noBlockingIssues: "No blocking issues — all rows except blanks are importable.",
      noReviewIssues: "No warnings — every importable row is fully valid.",
      statErrorHint: "Skipped on import",
      statWarningHint: "Import with empty fields",
      statValidHint: "No issues found",
      autoFixTitle: "Convert & fix data",
      autoFixIntro:
        "Adjust how values are converted before import. The preview updates when you change an option.",
      autoFixAlwaysOnTitle: "Always applied",
      autoFixAlwaysOn: [
        "Blank placeholders (-, N/A, - - - -) are treated as empty",
        "Duration text (1HR 2 MINS) is converted to minutes",
        "Multiple phones (986…/944…) uses the first valid number",
      ],
      autoFixInvalidPhoneLabel: "Import rows with invalid or missing phone numbers",
      autoFixInvalidPhoneHint:
        "Keeps the visit/customer row; phone is stored empty instead of blocking the import.",
      autoFixRefreshing: "Updating preview…",
    },
  },
  portal: {
    allStores: "All stores",
    allStaff: "All staff",
    calls: {
      title: "Call Users",
      subtitle: "Track retention and follow-up calls logged by your team",
      storeFilterLabel: "Store",
      staffFilterLabel: "Staff",
      searchLabel: "Search",
      searchPlaceholder: "Customer name, phone, or staff name",
      yearLabel: "Year",
      monthLabels: [
        "Jan",
        "Feb",
        "Mar",
        "Apr",
        "May",
        "Jun",
        "Jul",
        "Aug",
        "Sep",
        "Oct",
        "Nov",
        "Dec",
      ],
      queueLabel: "Call queue",
      segmentLabel: "Customer segment",
      valueTierLabel: "Ticket value",
      due: "Due",
      loadError: "Could not load call data. Please refresh and try again.",
      previousPage: "Previous",
      nextPage: "Next",
      pageLabel: "Page {page} of {total}",
      notesLabel: "Notes",
      columns: {
        staff: "Staff",
        store: "Store",
      },
      queues: [
        { key: "ALL", label: "All customers" },
        { key: "NOT_ANSWERED", label: "Not answered" },
        { key: "FOLLOW_UP", label: "Follow-up calls" },
      ],
      segments: [
        { key: "ALL", label: "All" },
        { key: "NEW", label: "New" },
        { key: "RETAINED", label: "Retained" },
        { key: "PURCHASED", label: "Purchased" },
        { key: "NOT_PURCHASED", label: "Not purchased" },
      ],
      valueTiers: [
        { key: "ALL", label: "All values" },
        { key: "HIGH", label: "High value" },
        { key: "MID", label: "Mid value" },
        { key: "LOW", label: "Low value" },
      ],
      valueTierLabels: {
        HIGH: "High value",
        MID: "Mid value",
        LOW: "Low value",
      },
      intentTierLabels: {
        HOT: "Hot intent",
        WARM: "Warm intent",
        COLD: "Cold intent",
        BROWSING: "Browsing",
      },
      intentFilterActive: "Showing visits with {intent} (from analytics drill-down)",
      purchaseStatusLabels: {
        PURCHASED: "Purchased",
        NOT_PURCHASED: "Not purchased",
        PENDING: "Pending",
      },
      customerTypeLabels: {
        NEW: "New",
        REPEAT: "Retained",
        VIP: "VIP",
      },
      queueStatusLabels: {
        RETENTION: "Retention",
        FOLLOW_UP: "Follow-up",
        NOT_ANSWERED: "Not answered",
      },
      callOutcomeLabels: {
        ANSWERED: "Answered",
        NOT_ANSWERED: "Not answered",
        NOT_CALLED: "Not called yet",
      },
    },
    fieldSales: {
      title: "Field Sales",
      subtitle: "Outdoor GHS/JPP enrollment activity logged by your team",
      storeFilterLabel: "Store",
      staffFilterLabel: "Staff",
      searchLabel: "Search",
      searchPlaceholder: "Customer name, phone, or staff name",
      yearLabel: "Year",
      monthLabels: [
        "Jan",
        "Feb",
        "Mar",
        "Apr",
        "May",
        "Jun",
        "Jul",
        "Aug",
        "Sep",
        "Oct",
        "Nov",
        "Dec",
      ],
      loadError: "Could not load field sales. Please refresh and try again.",
      previousPage: "Previous",
      nextPage: "Next",
      pageLabel: "Page {page} of {total}",
      notesLabel: "Notes",
      followUpDue: "Follow-up due",
      columns: {
        staff: "Staff",
        store: "Store",
        schemes: "Schemes pitched",
        reason: "Reason",
      },
      analyticsFilterActive: "Filtered from analytics drill-down (outcome or activity type)",
    },
  },
} as const;

export type Content = typeof content;
