/** Canonical field keys → known header aliases (global, cross-feature) */
export const SYNONYM_MAP: Record<string, string[]> = {
  name: [
    "customer name",
    "client name",
    "party name",
    "member name",
    "cust name",
    "guest name",
    "visitor name",
    "name of customer",
    "full name",
    "customer",
    "client",
    "party",
    "member",
    "guest",
    "visitor",
    "naam",
  ],
  phone: [
    "mobile",
    "mob",
    "contact",
    "phone number",
    "cell",
    "mobile no",
    "mob no",
    "contact no",
    "whatsapp",
    "ph no",
    "phone no",
    "tel",
    "telephone",
    "cellphone",
    "contact number",
    "mobile number",
    "customer phone",
    "client phone",
    "whatsapp no",
  ],
  email: [
    "e-mail",
    "email address",
    "mail",
    "email id",
    "e mail",
    "customer email",
    "client email",
    "contact email",
  ],
  date: [
    "dt",
    "visit dt",
    "appointment",
    "appt",
    "date of visit",
    "visit date",
    "call date",
    "called on",
    "transaction date",
    "entry date",
    "log date",
    "created date",
    "date visited",
    "date called",
  ],
  amount: [
    "amt",
    "purchase",
    "sale",
    "total",
    "value",
    "bill amt",
    "bill amount",
    "transaction amount",
    "purchase amount",
    "sale amount",
    "revenue",
    "price",
    "total amount",
    "bill value",
    "invoice amount",
    "mrp",
    "final amount",
  ],
  staff: [
    "staff",
    "employee",
    "consultant",
    "attended by",
    "served by",
    "sales person",
    "salesperson",
    "rso",
    "executive",
    "agent",
    "agent name",
    "staff name",
    "employee name",
    "employee id",
    "staff id",
    "handled by",
    "assigned to",
  ],
  notes: [
    "note",
    "remarks",
    "comment",
    "comments",
    "description",
    "feedback",
    "staff notes",
    "observations",
    "details",
    "additional info",
  ],
  service: [
    "product",
    "service",
    "item",
    "category",
    "products explored",
    "product explored",
    "service type",
    "item type",
    "sku",
    "article",
    "collection",
  ],
  duration: [
    "call duration",
    "duration",
    "talk time",
    "call time",
    "length",
    "time on call",
    "minutes",
  ],
  outcome: [
    "call outcome",
    "result",
    "status",
    "call status",
    "disposition",
    "answer status",
    "answered",
    "response",
  ],
  visit_type: [
    "visit type",
    "type of visit",
    "walk in",
    "appointment type",
  ],
  purchase_status: [
    "purchase status",
    "purchased",
    "bought",
    "conversion",
    "sale status",
  ],
};

export function canonicalKeyForSynonym(header: string): string | null {
  const normalised = header.toLowerCase().trim();
  for (const [key, aliases] of Object.entries(SYNONYM_MAP)) {
    if (aliases.some((alias) => alias === normalised)) return key;
  }
  return null;
}
